# Generated by Django 5.2.7 on 2025-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="actu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=100)),
                ("contenu", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="actu_images/"),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
